//
//  main.cpp
//  Euler 2
//
//  Created by Aly Thobani on 16-01-05.
//  Copyright (c) 2016 __MyCompanyName__. All rights reserved.
//

/* Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

#include <iostream>

int main(int argc, const char * argv[])
{
    int firstfib = 1;
    int secondfib = 2;
    int sum = 2;
    int currentfib = firstfib + secondfib;
    int iterationcount = 0;
    while (currentfib <= 4000000) {
        if (currentfib % 2 == 0) sum += currentfib;
        firstfib = secondfib;
        secondfib = currentfib;
        currentfib = firstfib + secondfib;
        iterationcount++;
    }
    printf("sum of evens is %d\n", sum);
    printf("number of iterations was %d\n", iterationcount);
    return 0;
}

